### PR TITLE
Make example runnable using `cargo run --example`

### PR DESCRIPTION
**Pull request by panicbit**
This change is [Reviewable](https://reviewable.io/reviews/afshinm/juggernaut/1)

### CODE REVIEW

**Comment by afshinm** [comment]
thanks for tihs @panicbit 

The reason I made a separate project for this example was because I want to be able to compile the project to wasm / asmjs and update the readme as well. 

Let me know what you think.

**Comment by panicbit** [comment]
I think you should still be able to compile the example to wasm / asmjs (unless you can't pass `--target` in combination with `--example` to `cargo build`).

**Comment by panicbit** [comment]
If the example is supposed to get a lot bigger / more complex and needs a README then I think it's worth considering to create a seperate repo for the example.

**Comment by afshinm** [comment]
Right I see your point.

One last question, there is no Cargo.toml file now so where is the dependency? 
is this going to use the root folder as the dependency? or it is better to ask: how to compile this single file that needs another dependency?

**Comment by panicbit** [comment]
Dependencies for examples are usually added in the root Cargo.toml under the [`dev-dependencies` section](http://doc.crates.io/specifying-dependencies.html#development-dependencies).

edit: Unless the dependency is already in the `dependencies` section of course.

**Comment by afshinm** [comment]
thanks @panicbit!

**Pull request merged**
