### PR TITLE
Adding shuffle data option, implementing Softmax derivative and fixing train method issues

### PR DESCRIPTION
**Pull request by afshinm**

### CODE REVIEW

**Comment by scriptandcompile** [comment]
This definitely works, and let me say again I'm amazed how fast you are cranking away on this, but I'm not a fan of the set_shuffle idea. This seems to scream 'strategy' pattern here. 

If I had finished the builder pattern before this than adding in these features would be much nicer and cleaner, I just haven't had the time >.<

But as they say, perfect is the enemy of progress; I'm glad to see you making so much amazing progress. Keep up the work =D

**Comment by afshinm** [comment]
thanks @addtheice! I had a few issues with the models I have built. I read that shuffling data and bias node can help to fit the data easier /  faster.

Btw, this is the latest result I got tonight:

kapture 2017-09-26 at 21 27 47

Cool, isn't it? :D 

I will write a blog post soon.

**Comment by afshinm** [comment]
but let me know if you have a better idea for that shuffle_data thing. Happy to change it.

**Comment by scriptandcompile** [comment]
Ok, that's freaking awesome looking man.

Yeah, usually a bool flag which turns on and off a feature is usually (but not always) a sign of a code smell. one is no big deal, but it usually means you have some kind of either a strategy pattern to apply, or less commonly, a command pattern to apply.

In this case it might be a pipeline of commands.

Not sure how familiar you are with design patterns (it's awesome to learn them, just avoid going crazy gung ho on them. It's real easy to start hammer/nailing with design patterns).

The reason I like them is mainly because it allows for a common vocabulary for solving common repeating patterns.

It appears to me that what we have here is an optional command for applying training, something that isn't always wanted but commonly will be, but also one which will probably be mixed in with other common behaviour commands as well.

I still think the builder pattern is more important to implement on the network than this. Mostly because it has a builder 'feel' to it. Set up a bunch of things, wire them together, then run it. Screams builder/factory to me. Only thing to watch for is that we don't want to just limit ourselves entirely. in the future we might want to rewire networks during runtime instead of just building and running them. I don't see it as an issue, just something we don't want to block off in the future without a major reason.

That also seems like a space with little research. Sure, lots of dynamically built networks (lots in the GA space for example), but little in dynamic construction through it's lifetime for example.

**Pull request merged**
